### ISSUE TITLE
Can't terminate process from VS Code

### ISSUE THREAD

**Issue by Kantankerus** [loganch/AutoIt-VSCode#35] opened 2018-08-09 16:47 UTC
Visual Studio Code
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

SciTE 4.1.0 

AutoIt v3.3.14.5

AutoIt Plugin 0.2.0

Tried with only AutoIt Plugin enabled.

I *do* have a Pause/Break key on my keyboard (Logitech G Pro)
It works fine in SciTE.
Decided to mod AutoIt3Wrapper.ini to give it another termination sequence of (Ctrl+PGDN)...after modding ini and restarting VS Code and SciTE AutoIt3Wrapper displays:
`--> Press Ctrl+Alt+Break to Restart or Ctrl+Break -or- Ctrl+PGDN to Stop`
...but starting a simple timed loop and hitting Ctrl+PGDN in VS Code results in:
`! Program will be cancelled.`
...but does nothing.
Both Ctrl+Break and Ctrl+PGDN now work flawlessly inside SciTE itself, giving me:
```
--> Press Ctrl+Alt+Break to Restart or Ctrl+Break -or- Ctrl+PGDN to Stop
! Program will be cancelled.

>Process failed to respond; forcing abrupt termination...
>Exit code: 1    Time: 10.99
```

What am I doing wrong?

**Comment by loganch** [comment] 2018-11-08 18:05
Was Ctrl+Break not working in VSCode? I just discovered that on my Logitech G710+ that Scroll Lock must be on for AutoIt3Wrapper to consider the Pause/Break button to be 'Break'. 

I'm not sure about the Ctrl+PGDN issue because all the shortcuts are supposed to be handled by the Wrapper, which is itself an AutoIt script that implements the shortcuts with HotKeySet().

**Comment by Superbrka** [comment] 2019-04-05 04:56
Version: 1.34.0-insider (user setup)
Commit: 5fb8764a0b2cfd1cedd522f3b33eda7195da3e36
Date: 2019-04-04T22:33:57.657Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

SciTE 4.1.2
AutoIt v3.3.14.5
AutoIt Plugin 0.2.2

 I have the same issue that prevents me from closing/terminating processes. 
Ctrl+Break (or any other key combination) doesn't work for me. The only way is to kill the process over task manager.

Is there any bugfix or workaround planned for this issue ?

Thanks in advance

**Comment by loganch** [comment] 2019-04-05 06:27
Looked into the AutoItWrapper.au3, which handles the Stop and Restart shortcuts, and it looks like the problem is that the function connected to the Stop hotkey sends a menu command to SciTe.

I'll investigate a way to have VS Code take the shortcut to produce a similar effect.

**Comment by chillbest** [comment] 2019-05-29 15:36
> Looked into the AutoItWrapper.au3, which handles the Stop and Restart shortcuts, and it looks like the problem is that the function connected to the Stop hotkey sends a menu command to SciTe.
> 
> I'll investigate a way to have VS Code take the shortcut to produce a similar effect.

please quickly.  The Problem is killing me.

**Comment by loganch** [comment] 2019-05-30 05:08
Let me know if it works for you in v0.2.3.

**Comment by Superbrka** [comment] 2019-06-03 06:51
Nice, it's working for me now.

Thank you for your efforts !


Version: 1.35.0-insider (user setup)
Commit: 0284236851a94b116f468345f6e98688a737015d
Date: 2019-05-31T21:32:42.295Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Closed** 2019-07-19 19:03 UTC
